"""empty message

Revision ID: 0df98d2850af
Revises: 49ff777b9782
Create Date: 2023-04-26 13:51:18.139408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0df98d2850af'
down_revision = '49ff777b9782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concession_item', schema=None) as batch_op:
        batch_op.drop_column('item_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concession_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_name', sa.VARCHAR(length=64), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
