"""empty message

Revision ID: 1f08f3f7f97b
Revises: 782e2edfefd5
Create Date: 2023-04-26 13:58:21.719530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f08f3f7f97b'
down_revision = '782e2edfefd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concession_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('popcorn', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('soda', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('hotdog', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('churros', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concession_item', schema=None) as batch_op:
        batch_op.drop_column('churros')
        batch_op.drop_column('hotdog')
        batch_op.drop_column('soda')
        batch_op.drop_column('popcorn')

    # ### end Alembic commands ###
