"""empty message

Revision ID: 40f99bf6a698
Revises: f3f27e9b5d1c
Create Date: 2023-04-25 13:30:19.510067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40f99bf6a698'
down_revision = 'f3f27e9b5d1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint('booking_seat_id_fkey', type_='foreignkey')
        batch_op.drop_column('seat_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seat_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('booking_seat_id_fkey', 'seat', ['seat_id'], ['id'])

    # ### end Alembic commands ###
