"""empty message

Revision ID: 56f0509b3aec
Revises: fc8af9166f24
Create Date: 2023-04-25 13:15:17.198760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56f0509b3aec'
down_revision = 'fc8af9166f24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=30), nullable=False))
        batch_op.drop_column('time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
