"""empty message

Revision ID: 6a3a4236ba8d
Revises: 8c049157418a
Create Date: 2023-04-25 13:32:24.412114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a3a4236ba8d'
down_revision = '8c049157418a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cinema_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'cinema', ['cinema_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cinema_id')

    # ### end Alembic commands ###
