"""empty message

Revision ID: 840be43245ef
Revises: 40f99bf6a698
Create Date: 2023-04-25 13:31:01.786418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '840be43245ef'
down_revision = '40f99bf6a698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seat_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'seat', ['seat_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('seat_id')

    # ### end Alembic commands ###
